### ISSUE TITLE
Streaming does not seem to work#2

### ISSUE THREAD

**Issue by taype** [nalaso/anthropic-vertex-ai#50]
### Description

I use this code should generate streaming output, but it does not， could you tell me why？

### Code example

export async function POST(request: Request) {
  const {
    id,
    messages,
    modelId,
  }: { id: string; messages: Array<Message>; modelId: string } =
    await request.json();
  const session = await auth();
  console.log('message:', messages);
  if (!session) {
    return new Response('Unauthorized', { status: 401 });
  }

  const model = models.find((model) => model.id === modelId);

  if (!model) {
    return new Response('Model not found', { status: 404 });
  }
  const modelInstance = vertexProvider(model.apiIdentifier);
  const coreMessages = convertToCoreMessages(messages);

  console.log('coreMessage:', coreMessages);
  //console.log('coreMessage2:', coreMessages2);
  const streamingData = new StreamData();
  //console.log(model.apiIdentifier);
  const result = await streamText({
    model: modelInstance,
    system: modelId === 'claude-3-5-coder' ? CodePrompt : regularPrompt,
    messages: coreMessages,
    maxSteps: 5,

    onFinish: async ({ responseMessages }) => {
      if (session.user && session.user.id) {
        try {
          const responseMessagesWithoutIncompleteToolCalls =
            sanitizeResponseMessages(responseMessages);
          //console.log("responseMessagesWithoutIncompleteToolCalls:",responseMessagesWithoutIncompleteToolCalls);
          await saveChat({
            id,
            messages: [
              ...coreMessages,
              ...responseMessagesWithoutIncompleteToolCalls,
            ],
            userId: session.user.id,
          });
        } catch (error) {
          console.error('Failed to save chat');
        }
      }

      streamingData.close();
    },
    experimental_telemetry: {
      isEnabled: true,
      functionId: 'stream-text',
    },
  });

  return result.toDataStreamResponse({
    data: streamingData,
  });
}

**Comment by nalaso** [comment]
can you create a codesandbox link replicating the same issue?

**Comment by taype** [comment]
Apologies, it's my mistake. The issue lies in my front-end code, which caused a bug in generating streaming output. Thank you for your response!

**Comment by taype** [comment]
when i use:
POST {{baseUri}}/chat/
Content-Type: application/json
cookie:authjs.csrf-token=5129c401b89ec31f4073eedf90602fa765fe23f70c76f6c91a25a53795f6e060%7Caad0ffe0fb3fd47efab8b6281052873aa8af1d6c70a09ac47eee03d8397e56cf; sidebar:state=true; model-id=gpt-4; authjs.callback-url=http%3A%2F%2Flocalhost%3A3000%2Flogin%3FcallbackUrl%3Dhttp%253A%252F%252Flocalhost%253A3000%252F; authjs.session-token=eyJhb


{
    "id": "6f17e198-231a-43c3-baf1-ad06f8fb67b3",
    "messages": [
        {
            "role": "user",
            "content": "how to run an untrust application in linux?"
        }
    ],
    "modelId": "claude-3-5-sonnet"
}

get the following info.
HTTP/1.1 200 OK
set-cookie: auth; Path=/; Expires=Thu, 26 Dec 2024 07:24:21 GMT; HttpOnly; SameSite=Lax
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch
content-type: text/plain; charset=utf-8
x-vercel-ai-data-stream: v1
Date: Tue, 26 Nov 2024 07:24:23 GMT
Connection: keep-alive
keep-alive: timeout=5
Transfer-Encoding: chunked

0:"To"
0:" run an untrusted application in Linux"
0:" safely, you can:"
0:"\n\n1. Use a sandbox like"
0:" Firejail:"
0:"\n```bash\nfirej"
0:"ail --private application-"
0:"name\n```\n\n2. Run"
0:" as a non-privileg"
0:"ed user:\n```bash\n./"
0:"application-name\n```\n\n3."
0:" Use flatpak ("
0:"if available):\n```"
0:"bash\nflatpak run application-"
0:"id\n```\n\n4"
0:". Create a container using"
0:" Docker:\n```bash\ndocker run"
0:" application-name\n```"
0:"\n\nThe safest approach"
0:" is using a sandbox or"
0:" container to isolate the application"
0:" from your system."
e:{"finishReason":"stop","usage":{"promptTokens":31,"completionTokens":129},"isContinued":false}
d:{"finishReason":"stop","usage":{"promptTokens":31,"completionTokens":129}}
**codesandbox link:**
https://codesandbox.io/p/github/taype/KubersCoder/main?import=true&workspaceId=a4b10314-27a1-433b-b512-52e67621d8d7&embed=1
