### ISSUE TITLE
Please add a GitHub workflow and publish from this repository

### ISSUE THREAD

**Issue by fry69** [nalaso/anthropic-vertex-ai#7]
Please add a GitHub workflow and publish from this repository so that what we get from the NPM registry is what we see here. Feel free to reuse my workflow -> https://github.com/fry69/anthropic-vertex-ai-provider/blob/main/.github/workflows/release.yml

Currently there is already a `0.0.4` version in the NPM registry, but the source code here is at `0.0.2` (It is just fixing the README.md mostly, but still).

**Comment by nalaso** [comment]
sure. I am adding it right now.

**Comment by nalaso** [comment]
Done
